language: node_js
node_js:
  - 10.16.3
dist: trusty
sudo: true
addons:
  chrome: stable
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - npm install
script:
  - npm test